os: linux
arch: ppc64le
dist: focal
sudo: required
services:
  - docker
language: go
go:
- "1.16.x"

install:
  - sudo apt update
  - sudo apt install -y python3 rpm lftp
  - printf "set ssl:verify-certificate false" >> ~/.lftprc

script:
  - python3 ftp_version.py
  - bash build.sh
  - bash release.sh
