os: linux
arch: ppc64le
dist: focal
sudo: required
services:
  - docker
language: go
go:
- "1.16.x"

script:
  - cd $GOPATH
  - mkdir -p src/github.com/docker/
  - cd src/github.com/docker/
  - git clone https://gitlab.com/gitlab-org/ci-cd/docker-machine.git
  - mv docker-machine machine
  - rm machine/mk/build.mk
  - cd machine/mk/
  - wget https://raw.githubusercontent.com/Unicamp-OpenPower/docker-machine-build/main/build.mk
  - ls
  - cd ..
  - TARGET_OS=linux TARGET_ARCH=ppc64le make build-x
  - cd bin
  - ls
  - ./docker-machine-Linux-ppc64le --version
